name: flutter_firebase_ui
description: Firebase auth UI, dart package try to mimic the firebaseUI.
version: 0.0.1
author: Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=1.8.0 <2.1.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    git:
      url: git://github.com/ypelud/plugins
      path: packages/firebase_auth

dev_dependencies:
  test: '>=0.12.0 <=0.13.0'
  flutter_test:
    sdk: flutter
