name: menu_swipe_helpers
description: Provide classes, interfaces and mixins that help creating applications with menu swipe.
version: 0.2.3
author: Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=1.8.0 <2.1.0"

dependencies:
  redux: ^2.0.2
  flutter_redux: "^0.3.5"
  flutter:
    sdk: flutter

dev_dependencies:
  test: '>=0.12.0 <=0.13.0'
  flutter_test:
    sdk: flutter
